"""empty message

Revision ID: 4d2d3cc0314e
Revises: 9e6c4de50780
Create Date: 2023-05-15 22:49:03.088536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2d3cc0314e'
down_revision = '9e6c4de50780'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('regions', sa.Integer(), nullable=False),
    sa.Column('delivery_hours', sa.JSON(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('courier',
                    sa.Column('courier_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('courier_type', sa.String(), nullable=False),
                    sa.Column('regions', sa.JSON(), nullable=False),
                    sa.Column('working_hours', sa.JSON(), nullable=False),
                    sa.PrimaryKeyConstraint('courier_id')
                    )
    op.create_table('courier_order',
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('complete_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.courier_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courier')
    op.drop_table('courier_order')
    op.drop_table('orders')
    # ### end Alembic commands ###
